version: '3'

services:
  flask_test:
    build: 
      context: ./flask_docker_test
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py flask_docker_test:flask_docker_test
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - nginx
    networks:
      - flask_net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80 
        published: 80
    networks:
      - flask_net

volumes:
  app_data:

networks:
  flask_net: